### Login
POST http://127.0.0.1:8080/login HTTP/1.1
cache-control: no-cache 
content-type: application/json

{
  "username":"username",
  "password":"password"
}

### add a todo item
POST http://127.0.0.1:8080/todo HTTP/1.1
cache-control: no-cache 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImM0MzQ1YjU2LWJlODAtNDUyNy1iOWI3LTY2Mzk3ZWY3NTQyMyIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYxMDk0NDEyMSwidXNlcl9pZCI6MX0.ZNugjNEr8zy6XSxiPnpgBg9hFmT789zT0Pl-dCDhpdE

{
  "title":"my first todo"
}

### logout
POST http://127.0.0.1:8080/logout HTTP/1.1
cache-control: no-cache 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImM0MzQ1YjU2LWJlODAtNDUyNy1iOWI3LTY2Mzk3ZWY3NTQyMyIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYxMDk0NDEyMSwidXNlcl9pZCI6MX0.ZNugjNEr8zy6XSxiPnpgBg9hFmT789zT0Pl-dCDhpdE

### Refresh token
POST http://127.0.0.1:8080/token/refresh HTTP/1.1
cache-control: no-cache 
content-type: application/json

{
  "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTE1NzMyODYsInJlZnJlc2hfdXVpZCI6IjQ5OWI3MDI2LTNjZjQtNGFjOC1hZDc4LTg4YzM1ZjIxYzFhYiIsInVzZXJfaWQiOjF9.9eq2uaLw3o02VaoqO6VAcaSUgFiddBPpiL6Nzk2JiCg"
}